---

- name: Install prerequisites
  ansible.builtin.import_tasks: prereq.yml

- name: Configure MongoDB APT repo
  ansible.builtin.import_tasks: repo.yml

- name: Install MongoDB packages (version pinned)
  ansible.builtin.import_tasks: install.yml

- name: OS tuning (limits, THP, swappiness)
  ansible.builtin.import_tasks: tuning.yml

- name: Configure mongod (conf, dirs)
  ansible.builtin.import_tasks: configure.yml

- name: Create/ensure users (admin + app)
  ansible.builtin.import_tasks: users.yml
